# System & JVM Memory tuning (Safe limits for Pentium / 7GB RAM)
org.gradle.jvmargs=-Xmx2048m -XX:+UnlockDiagnosticVMOptions
org.gradle.parallel=false
org.gradle.daemon=true

# Mandatory AndroidX configuration to suppress the migration warning
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
