<?php

namespace App\Filament\Resources\RechargeCardBatches;

use App\Filament\Resources\RechargeCardBatches\Pages\ListRechargeCardBatches;
use App\Filament\Resources\RechargeCardBatches\RelationManagers\CardsRelationManager;
use App\Models\RechargeCardBatch;
use App\Services\RechargeCardService;
use Barryvdh\DomPDF\Facade\Pdf;
use Filament\Actions\Action;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use BackedEnum;
use UnitEnum;

class RechargeCardBatchResource extends Resource
{
    protected static ?string $model = RechargeCardBatch::class;

    protected static string|BackedEnum|null $navigationIcon = 'heroicon-o-ticket';

    protected static ?string $navigationLabel = 'Recharge Cards';

    protected static string|UnitEnum|null $navigationGroup = 'Configuration';

    protected static bool $canCreate = false;

    public static function form(Schema $schema): Schema
    {
        return $schema->components([]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('network')->badge(),
                TextColumn::make('denomination')->money('NGN'),
                TextColumn::make('quantity'),
                TextColumn::make('status')
    ->badge()
    ->color(fn ($state): string => match ($state->value) {
        'completed' => 'success',
        'failed' => 'danger',
        default => 'gray',
    }),
                TextColumn::make('failure_reason')->limit(40)->placeholder('-'),
                TextColumn::make('generatedBy.name')->label('Generated By'),
                TextColumn::make('created_at')->dateTime()->sortable(),
            ])
            ->filters([
                SelectFilter::make('network')->options([
                    'mtn' => 'MTN', 'glo' => 'Glo', 'airtel' => 'Airtel', '9mobile' => '9mobile',
                ]),
                SelectFilter::make('status')->options([
                    'pending' => 'Pending', 'completed' => 'Completed', 'failed' => 'Failed',
                ]),
            ])
            ->headerActions([
                Action::make('generate')
                    ->label('Generate Batch')
                    ->icon('heroicon-o-plus')
                    ->schema([
                        Select::make('network')
                            ->options(['mtn' => 'MTN', 'glo' => 'Glo', 'airtel' => 'Airtel', '9mobile' => '9mobile'])
                            ->required(),
                        TextInput::make('denomination')->numeric()->required(),
                        TextInput::make('quantity')->numeric()->required()->minValue(1)->maxValue(1000),
                    ])
                    ->action(function (array $data) {
                        $batch = app(RechargeCardService::class)->generateBatch(
                            admin: auth('admin')->user(),
                            network: $data['network'],
                            denomination: (float) $data['denomination'],
                            quantity: (int) $data['quantity'],
                        );

                        Notification::make()
                            ->title($batch->status->value === 'completed' ? 'Batch generated successfully' : 'Batch generation failed')
                            ->color($batch->status->value === 'completed' ? 'success' : 'danger')
                            ->body($batch->failure_reason)
                            ->send();
                    }),
            ])
            ->recordActions([
                Action::make('download_pdf')
                    ->label('Download PDF')
                    ->icon('heroicon-o-document-arrow-down')
                    ->action(function (RechargeCardBatch $record) {
                        $cards = $record->cards->map(fn ($card) => [
                            'serial_number' => $card->serial_number,
                            'pin' => $card->pin,
                            'denomination' => $card->denomination,
                        ])->toArray();

                        if (empty($cards)) {
                            Notification::make()->title('This batch has no cards to export.')->warning()->send();

                            return;
                        }

                        return response()->streamDownload(
                            fn () => print(Pdf::loadView('reports.export', [
                                'title' => "Recharge Cards - {$record->network} Batch",
                                'from' => $record->created_at->toDateString(),
                                'to' => $record->created_at->toDateString(),
                                'columns' => array_keys($cards[0]),
                                'rows' => $cards,
                            ])->output()),
                            "recharge-cards-batch-{$record->id}.pdf"
                        );
                    }),
            ])
            ->defaultSort('created_at', 'desc');
    }

    public static function getRelations(): array
    {
        return [
            CardsRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListRechargeCardBatches::route('/'),
        ];
    }
}